swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:9009'
basePath: /api
tags:
  - name: default-fixtures-controller
    description: Default Fixtures Controller
paths:
  /fixtures/ranking:
    get:
      tags:
        - default-fixtures-controller
      summary: ranking
      operationId: rankingUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TeamDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/fixtures/result/{result}':
    post:
      tags:
        - default-fixtures-controller
      summary: captureResult
      operationId: captureResultUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: result
          in: path
          description: result
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  TeamDTO:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      points:
        type: integer
        format: int32
      position:
        type: integer
        format: int32
      score:
        type: integer
        format: int32
    title: TeamDTO
